#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-crul
Version  : 0.6.0
Release  : 6
URL      : https://cran.r-project.org/src/contrib/crul_0.6.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/crul_0.6.0.tar.gz
Summary  : HTTP Client
Group    : Development/Tools
License  : MIT
Requires: R-curl
Requires: R-httpcode
Requires: R-mime
Requires: R-urltools
BuildRequires : R-curl
BuildRequires : R-httpcode
BuildRequires : R-mime
BuildRequires : R-urltools
BuildRequires : clr-R-helpers

%description
and mocking HTTP requests. The package is built on R6, and takes

%prep
%setup -q -c -n crul

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531362684

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1531362684
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library crul
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library crul
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library crul
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library crul|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/crul/DESCRIPTION
/usr/lib64/R/library/crul/INDEX
/usr/lib64/R/library/crul/LICENSE
/usr/lib64/R/library/crul/Meta/Rd.rds
/usr/lib64/R/library/crul/Meta/features.rds
/usr/lib64/R/library/crul/Meta/hsearch.rds
/usr/lib64/R/library/crul/Meta/links.rds
/usr/lib64/R/library/crul/Meta/nsInfo.rds
/usr/lib64/R/library/crul/Meta/package.rds
/usr/lib64/R/library/crul/Meta/vignette.rds
/usr/lib64/R/library/crul/NAMESPACE
/usr/lib64/R/library/crul/NEWS.md
/usr/lib64/R/library/crul/R/crul
/usr/lib64/R/library/crul/R/crul.rdb
/usr/lib64/R/library/crul/R/crul.rdx
/usr/lib64/R/library/crul/doc/async.Rmd
/usr/lib64/R/library/crul/doc/async.html
/usr/lib64/R/library/crul/doc/crul_vignette.Rmd
/usr/lib64/R/library/crul/doc/crul_vignette.html
/usr/lib64/R/library/crul/doc/curl-options.Rmd
/usr/lib64/R/library/crul/doc/curl-options.html
/usr/lib64/R/library/crul/doc/how-to-use-crul.Rmd
/usr/lib64/R/library/crul/doc/how-to-use-crul.html
/usr/lib64/R/library/crul/doc/index.html
/usr/lib64/R/library/crul/help/AnIndex
/usr/lib64/R/library/crul/help/aliases.rds
/usr/lib64/R/library/crul/help/crul.rdb
/usr/lib64/R/library/crul/help/crul.rdx
/usr/lib64/R/library/crul/help/paths.rds
/usr/lib64/R/library/crul/html/00Index.html
/usr/lib64/R/library/crul/html/R.css
